# Generated by Django 6.0.2 on 2026-03-02 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "permissions": [("can_purchase", "Can purchase products")]
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_manage_product", "Can manage products")]
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"permissions": [("can_review", "Can leave reviews")]},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={
                "permissions": [("can_manage_store", "Can manage stores")]
            },
        ),
    ]
