# Generated by Django 6.0.2 on 2026-03-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={},
        ),
    ]
