# Generated by Django 6.0.2 on 2026-03-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "permissions": [
                    ("can_manage_store", "Can manage stores"),
                    ("can_manage_product", "Can manage products"),
                    ("can_purchase", "Can purchase products"),
                    ("can_review", "Can leave reviews"),
                ]
            },
        ),
    ]
